import test from 'node:test';
import assert from 'node:assert/strict';
import {database} from '../scripts/sqlite-adapter.mjs';
import worker from '../dist/server/index.js';
const base='https://example.test';
function setup(){const DB=database();return {DB,ADMIN_EMAILS:'owner@example.test'}}
function req(path,{admin=false,other=false,method='GET',data,origin=base}={}){const headers={};if(admin||other){headers['oai-authenticated-user-id']='verified-user';headers['oai-authenticated-user-email']=admin?'owner@example.test':'reader@example.test'}if(data){headers['Content-Type']='application/json';headers.Origin=origin}return new Request(base+path,{method,headers,body:data?JSON.stringify(data):undefined})}
const post={slug:'test-note',title:'Test record',excerpt:'Summary',category:'趋势观察',tags:['test'],publishedAt:'2024-05-12',pinned:false,access:'member',readMinutes:2,sections:[{heading:'Preview',text:'Public preview'},{heading:'Body',text:'PRIVATE TEST BODY'}],status:'draft',revision:0};
test('admin authorization, draft visibility, publishing, member boundary, revisions and persistence',async()=>{const env=setup();assert.equal((await worker.fetch(req('/api/admin/articles'),env)).status,401);assert.equal((await worker.fetch(req('/api/admin/articles',{other:true}),env)).status,403);let response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env);assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.revision,1);assert.equal((await worker.fetch(req('/api/articles/test-note'),env)).status,404);response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...saved,status:'published'}}),env);assert.equal(response.status,200);const published=await response.json();const guest=await(await worker.fetch(req('/api/articles/test-note'),env)).json();assert.equal(guest.sections.length,1);assert.equal(guest.locked,true);const owner=await(await worker.fetch(req('/api/articles/test-note',{admin:true}),env)).json();assert.equal(owner.sections.length,2);const summaries=await(await worker.fetch(req('/api/articles'),env)).json();assert(!JSON.stringify(summaries).includes('PRIVATE TEST BODY'));assert(summaries.some(a=>a.publishedAt==='2024-05-12'));response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:saved}),env);assert.equal(response.status,409);const again=await(await worker.fetch(req('/api/admin/articles',{admin:true}),{...env})).json();assert.equal(again.find(a=>a.slug==='test-note').revision,2);response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...published,status:'draft'}}),env);assert.equal(response.status,200);assert.equal((await worker.fetch(req('/api/articles/test-note'),env)).status,404);env.DB.sqlite.close()});
test('write requests reject cross-origin, invalid schema, duplicate slugs, and invalid references',async()=>{const env=setup();assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',origin:'https://evil.test',data:post}),env)).status,403);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...post,slug:'../bad'}}),env)).status,400);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env)).status,200);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env)).status,409);const w={symbol:'TEST',name:'Test',market:'A 股',stage:'准备',thesis:'Observation',invalidation:'Invalidation',updatedAt:'2024-05-12',articleSlug:'test-note',revision:0};assert.equal((await worker.fetch(req('/api/admin/watchlist',{admin:true,method:'PUT',data:w}),env)).status,400);const response=await worker.fetch(req('/api/admin/watchlist',{admin:true,method:'PUT',data:{...w,articleSlug:''}}),env);assert.equal(response.status,200);const all=await(await worker.fetch(req('/api/watchlist'),env)).json();assert(all.some(x=>x.symbol==='TEST'));env.DB.sqlite.close()});
test('missing database reports a recoverable failure',async()=>{assert.equal((await worker.fetch(req('/api/articles'),{})).status,503)});

test('research feed supports lifecycle, full-body search and paid preview boundaries',async()=>{const env=setup();const all=await(await worker.fetch(req('/api/posts'),env)).json();assert(all.every(p=>p.id&&p.contentType&&p.format&&Array.isArray(p.content)));const doge=await(await worker.fetch(req('/api/posts?symbol=doge&market='+encodeURIComponent('加密')+'&order=asc'),env)).json();assert.equal(doge.length,5);assert.equal(doge[0].trendStage,'准备');assert.equal(doge.at(-1).trendStage,'失效');assert(doge.every(p=>p.symbol==='DOGE'));const filtered=await(await worker.fetch(req('/api/posts?type='+encodeURIComponent('交易反馈')+'&stage='+encodeURIComponent('失效')+'&q='+encodeURIComponent('沿用')),env)).json();assert.equal(filtered.length,1);assert.equal(filtered[0].slug,'doge-0910');const source={...post,slug:'private-search',status:'published',contentType:'交易反馈',format:'short',symbol:'DOGE',market:'美股',sector:'Test sector',trendStage:'运行',images:[{url:'https://example.test/visible.png',alt:'Preview',isPreview:true},{url:'https://example.test/secret.png',alt:'Secret',isPreview:false}]};assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:source}),env)).status,200);const leak=await(await worker.fetch(req('/api/posts?q=PRIVATE%20TEST%20BODY'),env)).json();assert.equal(leak.length,0);const owner=await(await worker.fetch(req('/api/posts?q=PRIVATE%20TEST%20BODY',{admin:true}),env)).json();assert.equal(owner.length,1);const preview=await(await worker.fetch(req('/api/posts/private-search'),env)).json();assert.equal(preview.content.length,1);assert.equal(preview.images.length,1);assert.equal(preview.locked,true);const legacy=await(await worker.fetch(req('/api/articles/private-search'),env)).json();assert.equal(legacy.images.length,1);const sameSymbol=await(await worker.fetch(req('/api/posts?symbol=DOGE&market='+encodeURIComponent('美股')),env)).json();assert.equal(sameSymbol.length,1);env.DB.sqlite.close()});

test('legacy documents normalize without requiring destructive schema changes',async()=>{const {normalizePost,orderPosts,filterPosts,toArticleDocument}=await import('../server/post-model.mjs');const normalized=normalizePost(post);assert.equal(normalized.contentType,'观察更新');assert.equal(normalized.format,'long');assert.equal(normalized.isMemberOnly,true);assert.equal(toArticleDocument(normalized).excerpt,post.excerpt);const dates=[{...normalized,id:'new',updatedAt:'2026-09-10T10:00:00Z',publishedAt:'2026-09-10T10:00:00Z'},{...normalized,id:'old',updatedAt:'2026-08-10T10:00:00Z',publishedAt:'2026-08-10T10:00:00Z'}];assert.equal(orderPosts(dates,true)[0].id,'old');assert.equal(orderPosts(dates)[0].id,'new');assert.equal(filterPosts(dates,{month:'2026-08'})[0].id,'old')});

test('video library protects full sources and joins symbol research without changing posts API',async()=>{const {projectVideo}=await import('../server/video-model.mjs');const privateVideo={isMemberOnly:true,videoUrl:'https://private.test/full.mp4',previewUrl:'https://public.test/preview.mp4'};assert.equal(projectVideo(privateVideo).videoUrl,'');assert.equal(projectVideo(privateVideo).previewUrl,privateVideo.previewUrl);assert.equal(projectVideo(privateVideo,true).videoUrl,privateVideo.videoUrl);const env=setup();const library=await(await worker.fetch(req('/api/library'),env)).json();assert.equal(library.videos.length,6);assert(library.videos.filter(v=>v.isMemberOnly).every(v=>v.locked&&!v.videoUrl));const postIds=new Set((await(await worker.fetch(req('/api/posts'),env)).json()).flatMap(p=>[p.id,p.slug]));for(const v of library.videos){assert(v.relatedPosts.every(id=>postIds.has(id)));assert(v.relatedVideos.every(id=>library.videos.some(x=>x.id===id)))}for(const c of library.courses)for(const ch of c.chapters)for(const l of ch.lessons)assert(l.contentType==='video'?library.videos.some(v=>v.id===l.contentId):postIds.has(l.contentId));const feed=await(await worker.fetch(req('/api/feed?symbol=DOGE&market='+encodeURIComponent('加密')),env)).json();assert.equal(feed.length,6);assert(feed.some(p=>p.video?.id==='video-06'));const onlyVideos=await(await worker.fetch(req('/api/feed?type=video'),env)).json();assert.equal(onlyVideos.length,6);env.DB.sqlite.close()});
