import test from 'node:test';
import assert from 'node:assert/strict';
import {database} from '../scripts/sqlite-adapter.mjs';
import worker from '../dist/server/index.js';
const base='https://example.test';
function setup(){const DB=database();return {DB,ADMIN_EMAILS:'owner@example.test'}}
function req(path,{admin=false,other=false,method='GET',data,origin=base}={}){const headers={};if(admin||other){headers['oai-authenticated-user-id']='verified-user';headers['oai-authenticated-user-email']=admin?'owner@example.test':'reader@example.test'}if(data){headers['Content-Type']='application/json';headers.Origin=origin}return new Request(base+path,{method,headers,body:data?JSON.stringify(data):undefined})}
const post={slug:'test-note',title:'Test record',excerpt:'Summary',category:'趋势观察',tags:['test'],publishedAt:'2024-05-12',pinned:false,access:'member',readMinutes:2,sections:[{heading:'Preview',text:'Public preview'},{heading:'Body',text:'PRIVATE TEST BODY'}],status:'draft',revision:0};
test('admin authorization, draft visibility, publishing, member boundary, revisions and persistence',async()=>{const env=setup();assert.equal((await worker.fetch(req('/api/admin/articles'),env)).status,401);assert.equal((await worker.fetch(req('/api/admin/articles',{other:true}),env)).status,403);let response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env);assert.equal(response.status,200);const saved=await response.json();assert.equal(saved.revision,1);assert.equal((await worker.fetch(req('/api/articles/test-note'),env)).status,404);response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...saved,status:'published'}}),env);assert.equal(response.status,200);const published=await response.json();const guest=await(await worker.fetch(req('/api/articles/test-note'),env)).json();assert.equal(guest.sections.length,1);assert.equal(guest.locked,true);const owner=await(await worker.fetch(req('/api/articles/test-note',{admin:true}),env)).json();assert.equal(owner.sections.length,2);const summaries=await(await worker.fetch(req('/api/articles'),env)).json();assert(!JSON.stringify(summaries).includes('PRIVATE TEST BODY'));assert(summaries.some(a=>a.publishedAt==='2024-05-12'));response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:saved}),env);assert.equal(response.status,409);const again=await(await worker.fetch(req('/api/admin/articles',{admin:true}),{...env})).json();assert.equal(again.find(a=>a.slug==='test-note').revision,2);response=await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...published,status:'draft'}}),env);assert.equal(response.status,200);assert.equal((await worker.fetch(req('/api/articles/test-note'),env)).status,404);env.DB.sqlite.close()});
test('write requests reject cross-origin, invalid schema, duplicate slugs, and invalid references',async()=>{const env=setup();assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',origin:'https://evil.test',data:post}),env)).status,403);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:{...post,slug:'../bad'}}),env)).status,400);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env)).status,200);assert.equal((await worker.fetch(req('/api/admin/articles',{admin:true,method:'PUT',data:post}),env)).status,409);const w={symbol:'TEST',name:'Test',market:'A 股',stage:'准备',thesis:'Observation',invalidation:'Invalidation',updatedAt:'2024-05-12',articleSlug:'test-note',revision:0};assert.equal((await worker.fetch(req('/api/admin/watchlist',{admin:true,method:'PUT',data:w}),env)).status,400);const response=await worker.fetch(req('/api/admin/watchlist',{admin:true,method:'PUT',data:{...w,articleSlug:''}}),env);assert.equal(response.status,200);const all=await(await worker.fetch(req('/api/watchlist'),env)).json();assert(all.some(x=>x.symbol==='TEST'));env.DB.sqlite.close()});
test('missing database reports a recoverable failure',async()=>{assert.equal((await worker.fetch(req('/api/articles'),{})).status,503)});
