"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {request,useResource} from '@/lib/live';
export default function AdminLogin({register=false}:{register?:boolean}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const session=useResource<{signedIn:boolean;isAdmin:boolean;nickname:string}>('/api/session');
 useEffect(()=>{if(location.hash.includes('access_token')){history.replaceState(null,'',location.pathname);setNotice('邮箱确认完成，请使用邮箱和密码登录。')}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setNotice('');if(register&&password!==confirmation){setError('两次输入的密码不一致');return}setBusy(true);try{const result=await request<{confirmationRequired?:boolean;message?:string;isAdmin?:boolean}>('/api/auth/'+(register?'register':'login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,nickname:name})});setPassword('');setConfirmation('');if(result.confirmationRequired)setNotice(result.message||'请查看邮箱确认邮件，确认后返回登录。');else window.location.assign(result.isAdmin?'/admin/':'/profile/')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await request('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});window.location.assign('/login/')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <div className="member-status"><h2>{register?'创建账号':'邮箱登录'}</h2>{session.data?.signedIn?<><p>你好，{session.data.nickname}</p><div className="actions"><Link className="button" href="/profile/">个人中心</Link>{session.data.isAdmin&&<Link className="button secondary" href="/admin/">内容管理</Link>}<button className="button secondary" onClick={logout} disabled={busy}>退出登录</button></div></>:<form onSubmit={submit} className="account-form">{register&&<label>昵称<input required maxLength={32} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)}/></label>}<label>邮箱<input type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>密码<input type="password" autoComplete={register?'new-password':'current-password'} required minLength={register?8:undefined} maxLength={register?72:1024} value={password} onChange={e=>setPassword(e.target.value)}/></label>{register&&<><small>至少8个字符。注册后请通过邮件确认邮箱。</small><label>确认密码<input type="password" autoComplete="new-password" required value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label></>}<button className="button" disabled={busy}>{busy?'正在处理…':register?'注册账号':'登录'}</button><p>{register?'已有账号？':'还没有账号？'} <Link href={register?'/login/':'/register/'}>{register?'返回登录':'注册账号 →'}</Link></p></form>}{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}</div>;
}
