"use client";

import {formatPostTime} from '@/lib/postTime.mjs';
import BoldText from './BoldText';
import PostImages from './PostImages';
import VideoCard from './VideoCard';

import type {Post} from '@/lib/posts';
import {timelineHref,filterHref} from '@/lib/posts';
const tones={'观察更新':'observe','交易计划':'plan','交易反馈':'feedback','市场复盘':'review','教学内容':'lesson',video:'lesson'};
export default function PostCard({post,full=false,timeline=false,compact=false}:{post:Post;full?:boolean;timeline?:boolean;compact?:boolean}){if(post.video)return <article className="research-record" id={'record-'+post.slug}><VideoCard video={post.video} feed/></article>;const inline=post.format==='short'||full;const short=compact&&post.format==='short'&&!full;return <article className={'research-record '+(timeline?'timeline-record':'')+(short?' compact-short':compact?' compact-long':'')} id={'record-'+post.slug}><header className="record-heading"><div className="record-subject">{post.symbol&&<a className="symbol-chip" href={timelineHref(post.symbol,post.market)}>{post.symbol}</a>}{post.timeframe&&<span className="timeframe">· {post.timeframe}</span>}</div><div className="record-badges"><span className={'record-type type-'+tones[post.contentType]}>{post.contentType}</span>{post.trendStage&&<span className={'record-stage record-stage-'+post.trendStage}>{post.trendStage}</span>}{post.isPinned&&!timeline&&<span className="record-pin">置顶</span>}</div></header>{!compact&&post.format!=='short'&&<><h3 className="record-title">{post.statusText||post.title}</h3>{!compact&&post.statusText&&post.statusText!==post.title&&<p className="record-deck">{post.title}</p>}</>}{inline?<div className="record-body">{post.content.map((b,i)=><section key={i}>{b.heading&&(post.format==='short'?<p>{b.heading}</p>:<h4>{b.heading}</h4>)}<p>{post.format==='short'?<BoldText text={b.text}/>:b.text}</p></section>)}</div>:<p className="record-summary">{compact&&(post.statusText||post.title)!==post.summary&&<><strong className="inline-summary-lead">{post.statusText||post.title}{/[。！？!?]$/.test(post.statusText||post.title)?'':'。'}</strong>{' '}</>}{post.summary}</p>}{!inline&&post.locked&&post.content[0]&&(!compact||post.content[0].text!==post.summary)&&<div className="record-preview"><p>{post.content[0].text}</p></div>}<PostImages images={post.images}/>{post.locked&&compact?<div className="compact-member-note">会员内容 · 公开预览 <a href="/membership/">了解会员 ↗</a></div>:post.locked&&<div className="member-preview-note"><span>会员研究 · 公开预览</span><p>这里展示部分研究记录。有效会员可阅读完整内容，请在会员中心查看状态或联系管理员开通。</p><a href="/membership/">了解会员空间 ↗</a></div>}<footer className="record-footer"><div className="record-bottom-meta"><time dateTime={post.updatedAt||post.publishedAt}>{formatPostTime(post.updatedAt,post.publishedAt,!compact)}</time><span>{post.market}</span>{post.sector&&<a href={filterHref('q',post.sector)}>{post.sector}</a>}</div><div className="record-tags">{post.tags.map(tag=><a key={tag} href={filterHref('tag',tag)}>#{tag}</a>)}</div><div className="record-footline"><span>{post.author.name} · {post.isMemberOnly?'会员内容':'公开记录'}{post.isExample?' · 教学示例':''}</span>{!full&&post.format==='long'?<a href={'/article/?slug='+encodeURIComponent(post.slug)}>查看完整内容 <span>↗</span></a>:!full&&post.symbol?<a href={timelineHref(post.symbol,post.market)}>查看标的历史 ↗</a>:null}</div></footer></article>}
