"use client";

import PostImages from './PostImages';
import VideoCard from './VideoCard';
import {useState} from 'react';
import type {Post,PostImage} from '@/lib/posts';
import {timelineHref,filterHref,formatTime} from '@/lib/posts';
const tones={'观察更新':'observe','交易计划':'plan','交易反馈':'feedback','市场复盘':'review','教学内容':'lesson',video:'lesson'};
function ResearchImage({image}:{image:PostImage}){const [failed,setFailed]=useState(false);return <figure className="research-image">{failed?<div className="image-failed">图表暂时无法显示</div>:<a href={image.url} target="_blank" rel="noreferrer"><img src={image.url} alt={image.alt} loading="lazy" onError={()=>setFailed(true)}/></a>}{image.caption&&<figcaption>{image.caption}</figcaption>}</figure>}
function ShortLead({text}:{text:string}){const match=text.match(/^([\s\S]*?[。！？!?])([\s\S]*)$/);if(!match)return <>{text}</>;return <><strong className="short-lead">{match[1]}</strong>{match[2]}</>}
export default function PostCard({post,full=false,timeline=false,compact=false}:{post:Post;full?:boolean;timeline?:boolean;compact?:boolean}){if(post.video)return <article className="research-record" id={'record-'+post.slug}><VideoCard video={post.video} feed/></article>;const inline=post.format==='short'||full;const short=compact&&post.format==='short'&&!full;return <article className={'research-record '+(timeline?'timeline-record':'')+(short?' compact-short':compact?' compact-long':'')} id={'record-'+post.slug}><header className="record-heading"><div className="record-subject">{post.symbol?<a className="symbol-chip" href={timelineHref(post.symbol,post.market)}>{post.symbol}</a>:<span className="topic-label">{post.contentType==='教学内容'?'交易方法':'市场研究'}</span>}{post.timeframe&&<span className="timeframe">· {post.timeframe}</span>}</div><div className="record-badges"><span className={'record-type type-'+tones[post.contentType]}>{post.contentType}</span>{post.trendStage&&<span className={'record-stage record-stage-'+post.trendStage}>{post.trendStage}</span>}{post.isPinned&&!timeline&&<span className="record-pin">置顶</span>}</div></header>{!short&&<><h3 className="record-title">{post.statusText||post.title}</h3>{!compact&&post.statusText&&post.statusText!==post.title&&<p className="record-deck">{post.title}</p>}</>}{inline?<div className="record-body">{post.content.map((b,i)=><section key={i}>{b.heading&&<h4>{b.heading}</h4>}<p>{short&&i===0&&!b.heading?<ShortLead text={b.text}/>:b.text}</p></section>)}</div>:<p className="record-summary">{post.summary}</p>}{!inline&&post.locked&&post.content[0]&&(!compact||post.content[0].text!==post.summary)&&<div className="record-preview"><p>{post.content[0].text}</p></div>}{compact?<PostImages images={post.images}/>:post.images.slice(0,full?post.images.length:1).map((image,i)=><ResearchImage key={image.url+i} image={image}/>)}{post.locked&&compact?<div className="compact-member-note">会员内容 · 公开预览 <a href="/membership/">了解会员 ↗</a></div>:post.locked&&<div className="member-preview-note"><span>会员研究 · 公开预览</span><p>这里保留部分研究记录。完整内容供会员阅读，会员开通暂未开放。</p><a href="/membership/">了解会员空间 ↗</a></div>}<footer className="record-footer"><div className="record-bottom-meta"><time dateTime={post.updatedAt}>{compact?post.updatedAt.slice(5,10):formatTime(post.updatedAt)}</time><span>{post.market}</span>{post.sector&&<a href={filterHref('q',post.sector)}>{post.sector}</a>}</div><div className="record-tags">{post.tags.map(tag=><a key={tag} href={filterHref('tag',tag)}>#{tag}</a>)}</div><div className="record-footline"><span>{post.author.name} · {post.isMemberOnly?'会员内容':'公开记录'}{post.isExample?' · 教学示例':''}</span>{!full&&post.format==='long'?<a href={'/article/?slug='+encodeURIComponent(post.slug)}>查看完整内容 <span>↗</span></a>:!full&&post.symbol?<a href={timelineHref(post.symbol,post.market)}>查看标的历史 ↗</a>:null}</div></footer></article>}
