"use client";
import {useState} from 'react';
import Link from 'next/link';
import {request,useResource} from '@/lib/live';
import ResourceState from './ResourceState';
import {MemberStatusSummary,type MemberSession} from './Membership';
type User=MemberSession&{email:string;avatarUrl:string};
export default function Profile(){const session=useResource<User>('/api/session');if(!session.data)return <ResourceState error={session.error} retry={session.retry}/>;if(!session.data.signedIn)return <div className="reading"><h1>个人中心</h1><p>登录后可以设置昵称和头像，也可以查看会员开通方式。</p><div className="actions membership-entry-actions"><Link className="button membership-subscribe-button" href="/membership/subscribe/">开通会员</Link><Link className="button secondary" href="/login/">登录</Link><Link href="/register/">注册账号</Link></div></div>;return <>{session.error&&<p className="notice error" role="alert">登录状态暂时无法刷新，未保存的资料仍保留。{session.error}</p>}<Editor key={session.data.email} user={session.data}/></>}
function Editor({user}:{user:User}){const [name,setName]=useState(user.nickname),[savedName,setSavedName]=useState(user.nickname),[confirmLogoutAll,setConfirmLogoutAll]=useState(false),[avatar,setAvatar]=useState(''),[savedAvatar,setSavedAvatar]=useState(user.avatarUrl),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function choose(file:File){setError('');setNotice('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('请选择10MB以内的 JPG、PNG 或 WebP 图片');return}setBusy(true);try{const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#141617';ctx.fillRect(0,0,256,256);const side=Math.min(bitmap.width,bitmap.height);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);bitmap.close();setAvatar(canvas.toDataURL('image/jpeg',0.85));}catch{setError('图片无法读取，请重新选择。')}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await request<User>('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname:name,...(avatar?{avatarData:avatar}:{})})});setName(result.nickname);setSavedName(result.nickname);setConfirmLogoutAll(false);setSavedAvatar(result.avatarUrl);setAvatar('');setNotice('个人资料已保存');window.dispatchEvent(new Event('research-session-change'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function logout(allDevices=false){if(busy||allDevices&&!confirmLogoutAll)return;setBusy(true);setError('');setNotice('');try{await request(allDevices?'/api/auth/logout-all':'/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.assign('/login/')}catch(e){setError((e as Error).message);setBusy(false)}}
 const unsaved=name!==savedName||!!avatar;
 return <div className="reading"><h1>个人中心</h1><p className="muted">{user.email}</p><section className="profile-membership"><MemberStatusSummary user={user}/><div className="actions membership-entry-actions"><Link className="button membership-subscribe-button" href="/membership/subscribe/">开通会员</Link><Link className="button secondary" href="/membership/">查看会员中心 →</Link></div></section><form className="account-form" onSubmit={save}><fieldset disabled={busy}><div className="profile-avatar">{avatar||savedAvatar?<img src={avatar||savedAvatar} alt="头像预览"/>:<span>{name.slice(0,1)||'研'}</span>}</div><label>修改头像<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void choose(file)}}/></label><small>选择图片后会裁剪为方形头像，点击保存生效。</small><label>昵称<input required maxLength={32} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)}/></label><button className="button" disabled={busy}>{busy?'正在保存…':'保存资料'}</button></fieldset></form>{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<section className="profile-security"><h2>登录与设备</h2><p>可以只退出当前设备，或同时退出所有已登录的设备。</p><div className="actions">{user.isAdmin&&<Link className="button secondary" href="/admin/">内容管理</Link>}<button className="button secondary" disabled={busy} onClick={()=>logout()}>退出当前设备</button><button className="button secondary" disabled={busy||confirmLogoutAll} onClick={()=>{setConfirmLogoutAll(true);setError('');setNotice('')}}>退出所有设备</button></div>{confirmLogoutAll&&<section className="notice profile-logout-confirm" role="group" aria-label="退出所有设备确认"><p>确认退出所有设备？这包含当前设备，之后需要重新登录。</p>{unsaved&&<p className="unsaved-warning">你有未保存的昵称或头像修改，退出后这些修改将丢失。可以取消退出并先保存资料。</p>}<div className="actions"><button className="button" disabled={busy} onClick={()=>logout(true)}>{busy?'正在退出…':'确认退出所有设备'}</button><button className="button secondary" disabled={busy} onClick={()=>setConfirmLogoutAll(false)}>取消</button></div></section>}</section></div>
}
