"use client";
import WatchSync,{emptyWatchSync} from './WatchSync';
import ImageUploader from './ImageUploader';
import {useImageUploads} from '@/lib/useImageUploads';
import BoldTextarea from './BoldTextarea';
import {useState} from 'react';
import {request,useResource} from '@/lib/live';
import {CONTENT_TYPES,MARKETS,TREND_STAGES} from '@/lib/posts';
import type {WatchItem} from '@/lib/types';
export default function QuickComposer({watchItems,onPublished}:{watchItems:WatchItem[];onPublished?:()=>void}){
 const [sync,setSync]=useState(emptyWatchSync);const session=useResource<{isAdmin:boolean}>('/api/session');const [expanded,setExpanded]=useState(false);const [text,setText]=useState('');const [symbol,setSymbol]=useState('');const [timeframe,setTimeframe]=useState('');const [tags,setTags]=useState('');const [market,setMarket]=useState('跨市场');const [stage,setStage]=useState('');const [type,setType]=useState('观察更新');const [member,setMember]=useState(false);const uploads=useImageUploads();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [slug,setSlug]=useState(()=> 'note-'+Date.now().toString(36));
 async function publish(e:React.FormEvent){e.preventDefault();if(busy||uploads.blocked||!text.trim())return;setBusy(true);setError('');try{const item=watchItems.find(w=>w.symbol===symbol.trim().toUpperCase());const now=new Date();const date=now.toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'});await request('/api/admin/articles',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({watchSync:{...sync,revision:item?.revision??0},slug,title:text.trim().replaceAll('**','').split('\n')[0].slice(0,100),excerpt:text.trim().slice(0,600),sections:[{heading:'',text:text.trim()}],category:({'观察更新':'趋势观察','交易反馈':'趋势观察','交易计划':'交易计划','市场复盘':'市场复盘','教学内容':'趋势课程'} as Record<string,string>)[type],contentType:type,format:'short',symbol:symbol.trim().toUpperCase(),market,sector:'',trendStage:stage||null,statusText:'',timeframe:timeframe.trim(),tags:tags.split(/[,，]/).map(t=>t.trim().replace(/^#/, '')).filter(Boolean),images:uploads.images.map(image=>({...image,isPreview:!member})),publishedAt:date,publishedAtTime:now.toISOString(),pinned:false,access:member?'member':'public',readMinutes:1,status:'published',revision:0,isExample:false})});setText('');setSync(emptyWatchSync());uploads.reset();setSymbol('');setTimeframe('');setTags('');setSlug('note-'+Date.now().toString(36));setExpanded(false);setNotice('已发布，研究动态已更新。');onPublished?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!session.data?.isAdmin)return null;
 return <section className="quick-composer" aria-label="发布研究动态"><button className="composer-prompt" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><span className="composer-avatar">木</span><span>记录今天的观察……</span><small>{expanded?'收起':'写一条'}</small></button>{expanded&&(session.data?.isAdmin?<form onSubmit={publish}><fieldset disabled={busy} className="composer-fieldset"><ImageUploader uploads={uploads} disabled={busy}><BoldTextarea aria-label="观察正文" placeholder="记录结构的变化、等待的条件，或一次交易反馈……" value={text} maxLength={20000} onChange={e=>setText(e.target.value)} required/></ImageUploader><WatchSync value={sync} onChange={setSync} firstLine={text.replaceAll('**','').split(/[。！？\n]/)[0]}/><div className="composer-tools"><input aria-label="标的" placeholder="标的，如 BTC" value={symbol} maxLength={40} onChange={e=>setSymbol(e.target.value.toUpperCase())}/><input aria-label="周期" placeholder="周期，如 1H" value={timeframe} maxLength={30} onChange={e=>setTimeframe(e.target.value)}/><input aria-label="标签" placeholder="标签，逗号分隔" value={tags} maxLength={360} onChange={e=>setTags(e.target.value)}/><select aria-label="发布内容类型" value={type} onChange={e=>setType(e.target.value)}>{CONTENT_TYPES.filter(t=>t!=='video').map(t=><option key={t}>{t}</option>)}</select><select aria-label="发布市场" value={market} onChange={e=>setMarket(e.target.value)}>{MARKETS.map(m=><option key={m}>{m}</option>)}</select><select aria-label="发布阶段" value={stage} onChange={e=>setStage(e.target.value)}><option value="">阶段：不适用</option>{TREND_STAGES.map(s=><option key={s}>{s}</option>)}</select><label><input type="checkbox" checked={member} onChange={e=>setMember(e.target.checked)}/>会员可见</label><button type="submit" disabled={busy||uploads.blocked||!text.trim()}>{busy?'发布中…':uploads.uploading?'图片上传中…':'发布'}</button></div></fieldset>{error&&<p role="alert">{error}</p>}</form>:<p className="composer-signin">{session.error?'暂时无法确认登录状态。':session.data?'仅管理员可发布研究记录。':'正在确认登录状态…'} <a href="/login/" target="_top">管理员登录 ↗</a></p>)}{notice&&<p role="status">{notice}</p>}</section>
}
