"use client";

import {FormEvent, useCallback, useEffect, useMemo, useRef, useState} from "react";
import Link from "next/link";
import {ArrowLeft, Bell, BellOff, ChevronDown, ExternalLink, GripVertical, Headphones, LockKeyhole, Pause, Play, Plus, RefreshCw, RotateCcw, Search, Settings2, SlidersHorizontal, Volume2, VolumeX, X} from "lucide-react";
import TerminalChart, {TerminalChartStatus} from "@/components/TerminalChart";
import {request} from "@/lib/live";
import {defaultCapabilities, defaultConfig, dateLabel, panelTitles, type Capabilities, type ConfigResponse, type Connection, type FeedResponse, type FollowAccount, type MonitorSource, type Panel, type Preferences, type SourceState, type TerminalEvent, type View} from "@/lib/terminal-workbench";

type Session = {signedIn:boolean; nickname?:string; isMember?:boolean; membership?:{status:string;expiresAt:string|null}};
type Err = Error & {status?:number};

const initialConfig = {...defaultConfig, preferences:{...defaultConfig.preferences, panelSound:{...defaultConfig.preferences.panelSound}}};
const mobileViews:View[] = ["chart", "market", "selected", "smart"];
const marketFilters = ["全部", "加密资产", "股票", "指数", "外汇", "商品"];

function queryString(params:Record<string,string|number|undefined>) {
  const search = new URLSearchParams();
  Object.entries(params).forEach(([key,value]) => { if (value !== undefined && value !== "") search.set(key, String(value)); });
  const value = search.toString();
  return value ? `?${value}` : "";
}
function errorMessage(error:unknown) { return (error as Err)?.message || "请求失败，请稍后重试。"; }
function sourceStatus(sources:SourceState[]|undefined):Connection {
  if (!sources) return "connecting";
  if (sources.some(source=>source.status === "ok")) return "ok";
  if (sources.some(source=>source.status === "error")) return "error";
  if (sources.some(source=>source.status === "unconfigured")) return "unconfigured";
  return "disabled";
}
function connectionText(value:Connection) { return ({connecting:"连接中",ok:"已连接",error:"连接断开",unconfigured:"尚未配置",disabled:"已停用"} as Record<Connection,string>)[value]; }
function formatAgo(value:string) { const date = new Date(value); if (!Number.isFinite(date.getTime())) return "时间未知"; return new Intl.DateTimeFormat("zh-CN", {month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(date); }
function useStableEventIds(feed:FeedResponse|null) { return useMemo(()=>new Set((feed?.items||[]).map(item=>item.id)), [feed]); }

function StatusPill({status}:{status:Connection}) { return <span className={`terminal-status terminal-status-${status}`}><i aria-hidden="true"/>{connectionText(status)}</span>; }

function FeedItem({item}:{item:TerminalEvent}) {
  return <article className="workbench-event">
    <div className="workbench-event-meta"><span className="workbench-source">{item.sourceName}</span><time dateTime={item.publishedAt}>{formatAgo(item.publishedAt)}</time></div>
    <a className="workbench-event-title" href={item.url || "#"} target={item.url ? "_blank" : undefined} rel={item.url ? "noopener noreferrer nofollow" : undefined}>{item.title || "未命名消息"}<ExternalLink size={12} aria-hidden="true"/></a>
    {item.summary && <p>{item.summary}</p>}
    <div className="workbench-event-tags">{item.market && <span>{item.market}</span>}{item.tags?.slice(0,3).map(tag=><span key={tag}>{tag}</span>)}</div>
  </article>;
}

function FeedWindow({title,panel,feed,loading,error,paused,onPause,onLatest,newCount,onRefresh,onManage,showManage,sessionRequired,onScroll}:{title:string;panel:Panel;feed:FeedResponse|null;loading:boolean;error:string;paused:boolean;onPause:()=>void;onLatest:()=>void;newCount:number;onRefresh:()=>void;onManage?:()=>void;showManage?:boolean;sessionRequired?:boolean;onScroll?:(event:React.UIEvent<HTMLDivElement>)=>void}) {
  const status = sourceStatus(feed?.sources);
  return <section className={`workbench-window workbench-window-${panel}`} aria-label={title}>
    <header className="workbench-window-head"><div><div className="workbench-window-title"><span className="workbench-index">{panel === "market" ? "01" : panel === "selected" ? "02" : "03"}</span><h2>{title}</h2></div><div className="workbench-window-sub"><StatusPill status={status}/>{feed?.fetchedAt ? <span>更新 {formatAgo(feed.fetchedAt)}</span> : <span>等待数据</span>}</div></div><div className="workbench-window-actions"><button type="button" className="terminal-icon-button" onClick={onRefresh} aria-label={`刷新${title}`}><RefreshCw size={14}/></button>{onManage&&<button type="button" className={showManage?"terminal-icon-button is-active":"terminal-icon-button"} onClick={onManage} aria-label="管理监听"><Settings2 size={14}/></button>}</div></header>
    {sessionRequired && <div className="workbench-login-note"><LockKeyhole size={14}/><span>登录后管理个人监听；未接入来源会明确显示状态。</span><Link href="/login/?next=/terminal/">登录</Link></div>}
    <div className="workbench-feed-tools"><span className="workbench-unread" aria-live="polite">{feed?.items.length || 0} 条</span><span className="workbench-tool-spacer"/>{newCount > 0 && <button type="button" className="workbench-new-button" onClick={onLatest}>有 {newCount} 条新消息</button>}<button type="button" className="terminal-tool-button" onClick={onPause}>{paused?<><Play size={12}/>继续</>:<><Pause size={12}/>暂停</>}</button></div>
    {error&&<div className="workbench-inline-error" role="alert">{error}</div>}
    {!feed && loading ? <div className="workbench-empty"><RefreshCw className="terminal-spin" size={16}/>正在读取</div> : !feed?.items.length ? <div className="workbench-empty"><Bell size={16}/><span>{status === "unconfigured" ? "尚未接入消息源" : "暂时没有匹配消息"}</span></div> : <div className="workbench-feed-scroll" onScroll={onScroll}>{feed.items.map(item=><FeedItem key={item.id} item={item}/>)}</div>}
  </section>;
}

function SourceManager({config,capabilities,onSave,onClose}:{config:ConfigResponse["config"];capabilities:Capabilities;onSave:(next:ConfigResponse["config"])=>Promise<void>;onClose:()=>void}) {
  const [kind,setKind] = useState<MonitorSource["kind"]>("rss");
  const [name,setName] = useState(""); const [address,setAddress] = useState(""); const [keywords,setKeywords] = useState(""); const [sound,setSound] = useState(true); const [saving,setSaving] = useState(false); const [notice,setNotice] = useState("");
  const add = async (event:FormEvent) => { event.preventDefault(); setNotice(""); if (!address.trim()) { setNotice("请填写来源地址或账号。"); return; } const source:MonitorSource={id:`source-${Date.now().toString(36)}`,kind,name:name.trim()||"未命名来源",address:address.trim(),keywords,sound,enabled:true}; setSaving(true); try { await onSave({...config,sources:[...config.sources,source]}); setName("");setAddress("");setKeywords("");setNotice("已保存。实际监听状态请查看状态标签。"); } catch (e) { setNotice(errorMessage(e)); } finally { setSaving(false); } };
  const remove = async (id:string) => { const next=config.sources.filter(item=>item.id!==id); setSaving(true); try { await onSave({...config,sources:next}); } catch(e) {setNotice(errorMessage(e));} finally{setSaving(false);} };
  const toggle = async (source:MonitorSource) => { setSaving(true); try { await onSave({...config,sources:config.sources.map(item=>item.id===source.id?{...item,enabled:!item.enabled}:item)}); } catch(e){setNotice(errorMessage(e));} finally{setSaving(false);} };
  return <div className="workbench-manager"><div className="workbench-manager-head"><div><span className="workbench-kicker">SOURCE CONTROL</span><h3>管理监听来源</h3></div><button type="button" className="terminal-icon-button" onClick={onClose} aria-label="关闭来源管理"><X size={16}/></button></div><form onSubmit={add} className="workbench-manager-form"><div className="workbench-form-grid"><label>对象类型<select value={kind} onChange={e=>setKind(e.target.value as MonitorSource["kind"])}><option value="rss">新闻源 URL（RSS）</option><option value="x" disabled={!capabilities.x}>社交账号（X）{!capabilities.x?" · 待接入":""}</option><option value="wallet" disabled={!capabilities.wallet}>链上钱包{!capabilities.wallet?" · 待接入":""}</option></select></label><label>名称 / 备注<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：官方公告"/></label></div><label>地址或账号<input value={address} onChange={e=>setAddress(e.target.value)} placeholder={kind === "rss"?"https://example.com/feed.xml":"@账号或公开地址"}/></label><label>关键词（可选）<input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="逗号分隔"/></label><label className="workbench-check"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> 新消息播放提示音</label><button type="submit" className="workbench-primary" disabled={saving}><Plus size={14}/>保存监听配置</button>{notice&&<p className="workbench-manager-notice">{notice}</p>}</form><div className="workbench-config-list">{config.sources.map(source=><div className="workbench-config-row" key={source.id}><div><b>{source.name}</b><small>{source.kind.toUpperCase()} · {source.address}</small></div><div className="workbench-config-row-actions"><button type="button" className={source.enabled?"is-enabled":""} onClick={()=>void toggle(source)}>{source.enabled?"已启用":"已停用"}</button><button type="button" onClick={()=>void remove(source.id)} aria-label={`删除${source.name}`}><X size={13}/></button></div></div>)}{!config.sources.length&&<p className="workbench-muted">还没有保存的监听来源。</p>}</div></div>;
}

function SmartManager({config,capabilities,onSave}:{config:ConfigResponse["config"];capabilities:Capabilities;onSave:(next:ConfigResponse["config"])=>Promise<void>}) {
  const [platform,setPlatform]=useState<FollowAccount["platform"]>("hyperliquid"); const [name,setName]=useState(""); const [address,setAddress]=useState(""); const [notice,setNotice]=useState(""); const [saving,setSaving]=useState(false);
  const add=async(e:FormEvent)=>{e.preventDefault();if(!address.trim()){setNotice("请填写公开账户地址或标识。");return;}const wallet:FollowAccount={id:`wallet-${Date.now().toString(36)}`,platform,name:name.trim()||"未命名账户",address:address.trim(),enabled:true};setSaving(true);try{await onSave({...config,wallets:[...config.wallets,wallet]});setName("");setAddress("");setNotice("配置已保存；当前平台尚未接入实时数据适配器。");}catch(err){setNotice(errorMessage(err));}finally{setSaving(false);}};
  return <div className="workbench-smart-manager"><div className="workbench-smart-callout"><Headphones size={16}/><span>只接入公开或已授权记录，不请求交易权限。暂未接入时不会生成模拟交易。</span></div><form onSubmit={add} className="workbench-manager-form"><div className="workbench-form-grid"><label>平台<select value={platform} onChange={e=>setPlatform(e.target.value as FollowAccount["platform"])}><option value="hyperliquid">Hyperliquid {!capabilities.hyperliquid?"· 待接入":""}</option><option value="binance">Binance {!capabilities.binance?"· 待接入":""}</option></select></label><label>名称 / 备注<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：某交易员"/></label></div><label>公开账户地址或标识<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="不会请求交易权限"/></label><button className="workbench-primary" type="submit" disabled={saving}><Plus size={14}/>保存关注对象</button>{notice&&<p className="workbench-manager-notice">{notice}</p>}</form>{config.wallets.map(wallet=><div className="workbench-config-row" key={wallet.id}><div><b>{wallet.name}</b><small>{wallet.platform} · {wallet.address}</small></div><button type="button" onClick={()=>void onSave({...config,wallets:config.wallets.filter(item=>item.id!==wallet.id)})} aria-label={`删除${wallet.name}`}><X size={13}/></button></div>)}</div>;
}

export default function TerminalWorkspace() {
  const [session,setSession]=useState<Session|null>(null); const [config,setConfig]=useState(initialConfig); const [capabilities,setCapabilities]=useState<Capabilities>(defaultCapabilities); const [configLoading,setConfigLoading]=useState(true); const [configError,setConfigError]=useState("");
  const [market,setMarket]=useState<FeedResponse|null>(null); const [selected,setSelected]=useState<FeedResponse|null>(null); const [smart,setSmart]=useState<{items:TerminalEvent[];sources:SourceState[];accounts:FollowAccount[];fetchedAt:string}|null>(null); const [feedLoading,setFeedLoading]=useState(true); const [feedError,setFeedError]=useState("");
  const [activeView,setActiveView]=useState<View>("market"); const [search,setSearch]=useState(""); const [marketFilter,setMarketFilter]=useState("全部"); const [sourceFilter,setSourceFilter]=useState(""); const [paused,setPaused]=useState<Record<Panel,boolean>>({market:false,selected:false,smart:false}); const [newCounts,setNewCounts]=useState<Record<Panel,number>>({market:0,selected:0,smart:0});
  const [manager,setManager]=useState<"sources"|"smart"|null>(null); const [audioActive,setAudioActive]=useState(false); const [split,setSplit]=useState(config.preferences.splitRatio); const [chartStatus,setChartStatus]=useState<TerminalChartStatus>("loading");
  const previousIds=useRef<Record<Panel,Set<string>>>({market:new Set(),selected:new Set(),smart:new Set()}); const scrollAtLatest=useRef<Record<Panel,boolean>>({market:true,selected:true,smart:true}); const splitRef=useRef(split); const audioContext=useRef<AudioContext|null>(null);

  const refreshConfig=useCallback(async()=>{setConfigLoading(true);try{const current=await request<ConfigResponse>("/api/terminal/config");setConfig(current.config);setCapabilities(current.capabilities);setSplit(current.config.preferences.splitRatio);}catch(e){const err=e as Err;if(err.status!==401)setConfigError(errorMessage(e));}finally{setConfigLoading(false);}},[]);
  useEffect(()=>{void request<Session>("/api/session").then(setSession).catch(()=>setSession({signedIn:false}));void refreshConfig();},[refreshConfig]);
  const beep=useCallback((panel:Panel)=>{if(!audioActive||!config.preferences.sound||!config.preferences.panelSound[panel])return;try{const A=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!A)return;const ctx=audioContext.current||new A();audioContext.current=ctx;const o=ctx.createOscillator();const g=ctx.createGain();o.frequency.value=panel==="smart"?740:620;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.015,config.preferences.volume*.06),ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.18);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.2);}catch{/* user gesture required */}},[audioActive,config.preferences]);
  const mergeIncoming=(panel:Panel,data:FeedResponse)=>{const ids=new Set(data.items.map(item=>item.id));const previous=previousIds.current[panel];const fresh=previous.size?[...ids].filter(id=>!previous.has(id)).length:0;previousIds.current[panel]=ids;return fresh;};
  const fetchMarket=useCallback(async()=>{setFeedLoading(true);setFeedError("");try{const data=await request<FeedResponse>(`/api/terminal/news${queryString({q:search,market:marketFilter === "全部"?undefined:marketFilter,source:sourceFilter,limit:100})}`);const fresh=mergeIncoming("market",data);const held=paused.market||!scrollAtLatest.current.market;if(!held||!market){setMarket(data);if(!held)setNewCounts(current=>({...current,market:0}));}if(fresh&&held){setNewCounts(current=>({...current,market:current.market+fresh}));beep("market");}}catch(e){setFeedError(errorMessage(e));}finally{setFeedLoading(false);}},[marketFilter,paused.market,search,sourceFilter,beep,market]);
  const fetchSelected=useCallback(async()=>{if(!session?.signedIn){setSelected(null);return;}try{const data=await request<FeedResponse>(`/api/terminal/selected${queryString({q:search,market:marketFilter === "全部"?undefined:marketFilter,source:sourceFilter,limit:100})}`);const fresh=mergeIncoming("selected",data);const held=paused.selected||!scrollAtLatest.current.selected;if(!held||!selected){setSelected(data);if(!held)setNewCounts(current=>({...current,selected:0}));}if(fresh&&held){setNewCounts(current=>({...current,selected:current.selected+fresh}));beep("selected");}}catch(e){setSelected(null);setFeedError(errorMessage(e));}},[marketFilter,paused.selected,search,session?.signedIn,sourceFilter,selected,beep]);
  const fetchSmart=useCallback(async()=>{if(!session?.signedIn){setSmart(null);return;}try{const data=await request<{items:TerminalEvent[];sources:SourceState[];accounts:FollowAccount[];fetchedAt:string}>("/api/terminal/smart-money");setSmart(data);}catch(e){setFeedError(errorMessage(e));}},[session?.signedIn]);
  useEffect(()=>{if(configLoading)return;void fetchMarket();void fetchSelected();void fetchSmart();const timer=window.setInterval(()=>{if(document.visibilityState==="visible"){void fetchMarket();void fetchSelected();void fetchSmart();}},60000);return()=>window.clearInterval(timer);},[configLoading,fetchMarket,fetchSelected,fetchSmart]);
  useEffect(()=>{splitRef.current=split;},[split]);
  useEffect(()=>()=>{audioContext.current?.close().catch(()=>{});},[]);
  const updateConfig=useCallback(async(next:ConfigResponse["config"])=>{if(!session?.signedIn)throw new Error("请先登录后保存个人监听配置。");const result=await request<ConfigResponse>("/api/terminal/config",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});setConfig(result.config);setCapabilities(result.capabilities);setSplit(result.config.preferences.splitRatio);},[session?.signedIn]);
  const toggleAudio=()=>{if(!audioActive){setAudioActive(true);void audioContext.current?.resume();beep("market");}else{void updateConfig({...config,preferences:{...config.preferences,sound:false}}).catch(()=>{});setAudioActive(false);}};
  const enableAudio=async()=>{try{const A=window.AudioContext||(window as typeof window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(A){const ctx=audioContext.current||new A();audioContext.current=ctx;await ctx.resume();}setAudioActive(true);await updateConfig({...config,preferences:{...config.preferences,sound:true}});}catch(e){setFeedError(errorMessage(e));}};
  const resetLayout=async()=>{const next={...config,preferences:{...config.preferences,splitRatio:.38}};setSplit(.38);if(session?.signedIn)await updateConfig(next).catch(e=>setFeedError(errorMessage(e)));};
  const startSplit=(event:React.PointerEvent<HTMLDivElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>{const width=window.innerWidth;const next=Math.min(.55,Math.max(.28,(e.clientX/width)));setSplit(next);};const stop=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",stop);void updateConfig({...config,preferences:{...config.preferences,splitRatio:splitRef.current}}).catch(()=>{});};window.addEventListener("pointermove",move);window.addEventListener("pointerup",stop,{once:true});};
  const markLatest=(panel:Panel)=>{setNewCounts(c=>({...c,[panel]:0}));scrollAtLatest.current[panel]=true;setPaused(p=>({...p,[panel]:false}));if(panel==="market")void fetchMarket();else if(panel==="selected")void fetchSelected();};
  const visibleSmart=useMemo<FeedResponse|null>(()=>smart?{items:smart.items,sources:smart.sources,fetchedAt:smart.fetchedAt}:null,[smart]);
  const setPanelPause=(panel:Panel)=>setPaused(p=>({...p,[panel]:!p[panel]}));
  const feedFor=(panel:Panel)=>panel==="market"?market:panel==="selected"?selected:visibleSmart;
  const onChartStatus=(status:TerminalChartStatus)=>setChartStatus(status);
  const status=sourceStatus(market?.sources); const smartStatus=sourceStatus(smart?.sources);
  const onScroll=(panel:Panel,e:React.UIEvent<HTMLDivElement>)=>{const el=e.currentTarget;scrollAtLatest.current[panel]=el.scrollTop+el.clientHeight>=el.scrollHeight-24;};
  const feedPanel=(panel:Panel,title:string,sessionRequired=false)=><FeedWindow title={title} panel={panel} feed={feedFor(panel)} loading={feedLoading} error={feedError} paused={paused[panel]} onPause={()=>setPanelPause(panel)} newCount={newCounts[panel]} onLatest={()=>markLatest(panel)} onRefresh={()=>panel==="market"?void fetchMarket():panel==="selected"?void fetchSelected():void fetchSmart()} onManage={panel==="selected"?()=>setManager(v=>v==="sources"?null:"sources"):panel==="smart"?()=>setManager(v=>v==="smart"?null:"smart"):undefined} showManage={manager===(panel==="selected"?"sources":"smart")} sessionRequired={sessionRequired} onScroll={(event)=>onScroll(panel,event)}/>;

  return <div className="terminal-page" style={{"--terminal-split":`${split*100}%`} as React.CSSProperties}>
    <header className="terminal-topbar"><div className="terminal-brand"><Link href="/" className="terminal-back"><ArrowLeft size={15}/>返回主站</Link><span className="terminal-brand-divider"/><div><strong>交易终端</strong><small>RESEARCH WORKBENCH</small></div></div><div className="terminal-topbar-actions"><span className="terminal-connection"><i aria-hidden="true" className={`terminal-connection-dot terminal-connection-${status}`}/>{connectionText(status)}<span className="terminal-connection-detail">· 仅代表消息接口</span></span><button type="button" className={`terminal-top-button ${audioActive&&config.preferences.sound?"is-on":""}`} onClick={audioActive?toggleAudio:enableAudio} title={audioActive?"关闭提示音":"点击激活提示音"}>{audioActive&&config.preferences.sound?<Volume2 size={15}/>:<VolumeX size={15}/>}<span>{audioActive&&config.preferences.sound?"提示音已开":"提示音"}</span></button><button type="button" className="terminal-top-button" onClick={()=>setManager(manager?null:"sources")}><Settings2 size={15}/><span>设置</span></button></div></header>
    <div className="terminal-mobile-tabs" role="tablist" aria-label="终端视图"><button className={activeView==="chart"?"active":""} onClick={()=>setActiveView("chart")} role="tab">图表</button><button className={activeView==="market"?"active":""} onClick={()=>setActiveView("market")} role="tab">全市场</button><button className={activeView==="selected"?"active":""} onClick={()=>setActiveView("selected")} role="tab">自选</button><button className={activeView==="smart"?"active":""} onClick={()=>setActiveView("smart")} role="tab">聪明钱</button></div>
    <main className="terminal-main" aria-label="行情研究终端"><aside className={`terminal-monitor-area ${activeView!=="market"&&activeView!=="selected"&&activeView!=="smart"?"mobile-hidden":""}`}>
      <div className="terminal-filterbar"><div className="terminal-filter-search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索标题、摘要或资产" aria-label="搜索消息"/></div><select value={marketFilter} onChange={e=>setMarketFilter(e.target.value)} aria-label="市场类别">{marketFilters.map(filter=><option key={filter}>{filter}</option>)}</select><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)} aria-label="来源筛选"><option value="">全部来源</option>{(market?.sources||[]).map(source=><option value={source.id} key={source.id}>{source.name}</option>)}</select></div>
      <div className="terminal-desktop-panels">{feedPanel("market","全市场消息")}{feedPanel("selected","自选消息",true)}{feedPanel("smart","聪明钱动态",true)}</div>
      <div className="terminal-mobile-panels">{activeView==="market"&&feedPanel("market","全市场消息")}{activeView==="selected"&&feedPanel("selected","自选消息",true)}{activeView==="smart"&&feedPanel("smart","聪明钱动态",true)}</div>
      {manager==="sources"&&<SourceManager config={config} capabilities={capabilities} onSave={updateConfig} onClose={()=>setManager(null)}/>}
      {manager==="smart"&&<SmartManager config={config} capabilities={capabilities} onSave={updateConfig}/>}
      <div className="terminal-monitor-footer"><span>{session?.signedIn?`当前账号：${session.nickname||"已登录"}`:"访客模式：全市场消息可读"}</span><button type="button" onClick={()=>void refreshConfig()}><RefreshCw size={12}/>更新配置</button></div>
    </aside><div className="terminal-divider" role="separator" aria-label="拖动调整左右比例" tabIndex={0} onPointerDown={startSplit}><GripVertical size={14}/></div><section className={`terminal-chart-area ${activeView!=="chart"?"mobile-hidden":""}`} aria-label="TradingView K线图"><div className="terminal-chart-header"><div><span className="terminal-chart-kicker">MARKET CHART</span><strong>TradingView 高级图表</strong><span className="terminal-chart-state">{chartStatus==="ready"?"图表已加载":"图表加载中"}</span></div><button type="button" className="terminal-reset-button" onClick={()=>void resetLayout()}><RotateCcw size={13}/>恢复默认布局</button></div><div className="terminal-chart-host"><TerminalChart symbol="BINANCE:BTCUSDT" interval="60" onStatusChange={onChartStatus}/></div><div className="terminal-chart-note">图表由 TradingView 官方组件提供。品种搜索、周期、指标和绘图工具在图表内使用；图表只用于研究，不提供下单或自动交易。</div></section></main>
    {configError&&<div className="terminal-toast" role="status">{configError}</div>}
  </div>;
}
