"use client";
import {useEffect,useState} from 'react';
import {request} from '@/lib/live';
import {LEARNING_TOPICS} from '@/lib/library';
import {VIDEO_CONFIG} from '@/config/videos.mjs';
type Entry={id:string;revision:number;title:string;description:string;videoUrl:string;videoProvider:string;uploadId:string;duration:number;category:string;tags:string[];isMemberOnly:boolean;status:string};
const blank=():Entry=>({id:'video-'+crypto.randomUUID(),revision:0,title:'',description:'',videoUrl:'',videoProvider:'youtube',uploadId:'',duration:0,category:'市场专题',tags:[],isMemberOnly:false,status:'draft'});
export default function VideoStudio(){
 const [entry,setEntry]=useState<Entry>(blank),[list,setList]=useState<Entry[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState('');
 useEffect(()=>{request<Entry[]>('/api/admin/videos').then(setList).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 const change=(v:Partial<Entry>)=>{setEntry(e=>({...e,...v}));setNotice('')};
 async function upload(f:File){setFile(f);change({uploadId:''});setError('');if(!VIDEO_CONFIG.mimeTypes.includes(f.type)||f.size>VIDEO_CONFIG.maxFileBytes){setError('请选择50MB以内的 MP4 / WebM 视频');return}setBusy(true);setProgress(0);try{const ticket=await request<{id:string;uploadUrl:string}>('/api/admin/video-uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mimeType:f.type,fileSize:f.size})});await new Promise<void>((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',ticket.uploadUrl);xhr.setRequestHeader('Content-Type',f.type);xhr.timeout=VIDEO_CONFIG.uploadTimeoutMs;xhr.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error('上传失败，请重试'));xhr.onerror=()=>reject(new Error('网络中断，请重试'));xhr.ontimeout=()=>reject(new Error('上传超时，请重试'));xhr.send(f)});change({uploadId:ticket.id});setNotice('视频上传完成，可以发布。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(status:string){setBusy(true);setError('');setNotice('');try{const saved=await request<Entry>('/api/admin/videos',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...entry,status})});setEntry(saved);setList(v=>[saved,...v.filter(x=>x.id!==saved.id)]);setNotice(status==='published'?'视频已发布，知识库和首页动态流均可查看。':'已保存为草稿。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="editor-panel" style={{maxWidth:900,margin:'20px auto'}}><h2>视频管理</h2><p>接入 Bilibili / YouTube，或上传本地 MP4 / WebM。</p>{error&&<p className="notice error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<fieldset className="editor-fields" disabled={busy}><label>已有视频<select value={entry.revision?entry.id:''} onChange={e=>{const v=list.find(x=>x.id===e.target.value);setEntry(v||blank());setFile(null);setNotice('')}}><option value="">新建视频</option>{list.map(v=><option key={v.id} value={v.id}>{v.title} · {v.status==='published'?'已发布':'草稿'}</option>)}</select></label><label>视频来源<select value={entry.videoProvider==='selfHosted'?'upload':'link'} onChange={e=>{change({videoProvider:e.target.value==='upload'?'selfHosted':'youtube',videoUrl:'',uploadId:''});setFile(null)}}><option value="link">Bilibili / YouTube 链接</option><option value="upload">上传本地视频</option></select></label>{entry.videoProvider==='selfHosted'?<><label>选择视频（最大50MB）<input type="file" accept={VIDEO_CONFIG.accept} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label>{preview&&<video controls preload="metadata" src={preview} style={{width:'100%',maxWidth:640,aspectRatio:'16/9'}} onLoadedMetadata={e=>change({duration:Math.round(e.currentTarget.duration)||0})}/>}<small>{busy?`正在处理 / 上传 ${progress}%`:entry.uploadId?'文件已上传':'请选择视频文件'}</small>{file&&!entry.uploadId&&<button type="button" onClick={()=>upload(file)}>重试上传</button>}</>:<label>视频链接<input placeholder="https://www.bilibili.com/video/BV… 或 YouTube 链接" value={entry.videoUrl} onChange={e=>change({videoUrl:e.target.value})}/></label>}<label>视频标题<input maxLength={180} value={entry.title} onChange={e=>change({title:e.target.value})}/></label><label>简介<textarea rows={4} value={entry.description} onChange={e=>change({description:e.target.value})}/></label><div className="editor-row"><label>主题 / 分类<select value={entry.category} onChange={e=>change({category:e.target.value})}>{LEARNING_TOPICS.filter(t=>t!=='全部').map(t=><option key={t}>{t}</option>)}{!LEARNING_TOPICS.some(t=>t===entry.category)&&<option>{entry.category}</option>}</select></label><label>时长（秒）<input type="number" min={0} value={entry.duration} onChange={e=>change({duration:Number(e.target.value)})}/></label></div><label>标签（逗号分隔）<input value={entry.tags.join(',')} onChange={e=>change({tags:e.target.value.split(/[,，]/)})}/></label><label className="checkbox-label"><input type="checkbox" checked={entry.isMemberOnly} onChange={e=>change({isMemberOnly:e.target.checked})}/>会员内容</label><div className="editor-actions"><button className="button secondary" onClick={()=>save('draft')}>保存草稿 / 下架</button><button className="button" disabled={!entry.title.trim()||(entry.videoProvider==='selfHosted'&&!entry.uploadId)} onClick={()=>save('published')}>{entry.status==='published'?'更新视频':'发布视频'}</button>{entry.revision>0&&<a href={'/video/?id='+entry.id} target="_blank" rel="noreferrer">查看视频 ↗</a>}</div></fieldset></section>
}
