// Cloudflare Worker entry. Authentication headers are injected by Sites dispatch.
// Local development strips incoming identity headers before supplying its test identity.
import {videos,courses} from './library.mjs';
import {projectVideo,videoPost} from './video-model.mjs';
import {seedArticles,seedWatchlist} from './seed.mjs';
import {projectPost,filterPosts,orderPosts,CONTENT_TYPES,MARKETS,STAGES} from './post-model.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const categories=['趋势观察','市场复盘','趋势课程','交易计划'];
const stages=['准备','启动','运行','高潮','失效'];
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
function text(value,name,max,optional=false){if(typeof value!=='string'||value.length>max||(!optional&&!value.trim()))fail(`${name}不能为空，且不能超过 ${max} 字`);return value.trim();}
function date(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||(!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value))fail('日期格式不正确');return value;}
function article(input){const a={slug:text(input.slug,'文章标识',80),title:text(input.title,'标题',180),excerpt:text(input.excerpt,'摘要',600),category:input.category,tags:input.tags,publishedAt:date(input.publishedAt),pinned:input.pinned,access:input.access,readMinutes:input.readMinutes,sections:input.sections,status:input.status};if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(a.slug))fail('文章标识只能使用小写字母、数字和短横线');if(!categories.includes(a.category)||!['draft','published'].includes(a.status)||!['public','member'].includes(a.access)||typeof a.pinned!=='boolean')fail('文章分类、状态或权限不正确');if(!Number.isInteger(a.readMinutes)||a.readMinutes<1||a.readMinutes>180)fail('阅读时间应为 1–180 分钟');if(!Array.isArray(a.tags)||a.tags.length>12)fail('最多添加 12 个标签');a.tags=a.tags.filter(t=>typeof t!=='string'||t.trim()).map(t=>text(t,'标签',30));if(!Array.isArray(a.sections)||!a.sections.length||a.sections.length>80)fail('请填写 1–80 个正文段落');a.sections=a.sections.map(s=>({heading:text(s.heading,'段落标题',180,true),text:text(s.text,'段落正文',20000)}));a.id=input.id||a.slug;a.contentType=input.contentType||({'趋势观察':'观察更新','交易计划':'交易计划','市场复盘':'市场复盘','趋势课程':'教学内容'}[a.category]);a.format=input.format||'long';a.symbol=text(input.symbol||'','标的',40,true).toUpperCase();a.market=input.market||'跨市场';a.sector=text(input.sector||'','板块',80,true);a.trendStage=input.trendStage||null;a.statusText=text(input.statusText||'','状态说明',180,true);a.timeframe=text(input.timeframe||'','观察周期',30,true);if(!CONTENT_TYPES.includes(a.contentType)||!MARKETS.includes(a.market)||!['short','long'].includes(a.format)||(a.trendStage&&!STAGES.includes(a.trendStage)))fail('内容类型、市场、形式或趋势阶段不正确');a.publishedAtTime=typeof input.publishedAtTime==='string'&&input.publishedAtTime.startsWith(a.publishedAt)&&Number.isFinite(Date.parse(input.publishedAtTime))?input.publishedAtTime:a.publishedAt+'T10:00:00+08:00';a.updatedAt=new Date().toISOString();a.author={id:'sanmu',name:'三木'};a.isExample=input.isExample===true;a.tradeId=text(input.tradeId||'','交易编号',80,true)||null;a.watchlistId=text(input.watchlistId||'','观察编号',80,true)||null;a.relatedPosts=Array.isArray(input.relatedPosts)?input.relatedPosts.slice(0,30).map(v=>text(v,'关联记录',80)):[];if(input.images!==undefined&&!Array.isArray(input.images))fail('图片格式不正确');a.images=(input.images||[]).map(i=>{const url=text(i.url,'图片链接',2000);if(!(url.startsWith('/')&&!url.startsWith('//')&&!url.includes('\\')||/^https:\/\//.test(url)))fail('图片只支持本站路径或 HTTPS 地址');return {url,alt:text(i.alt,'图片说明',250),caption:text(i.caption||'','图注',400,true),isPreview:i.isPreview===true}});if(a.images.length>8)fail('每条记录最多 8 张图片');return a;}
function watch(input){const w={symbol:text(input.symbol,'观察标识',40),name:text(input.name,'名称',100),market:text(input.market,'市场',40),stage:input.stage,thesis:text(input.thesis,'观察依据',2000),invalidation:text(input.invalidation,'失效条件',2000),updatedAt:date(input.updatedAt),articleSlug:text(input.articleSlug,'关联文章',80,true)};if(!/^[A-Za-z0-9.-]+$/.test(w.symbol)||!stages.includes(w.stage))fail('观察标识或阶段不正确');return w;}
function identity(request,env){const id=request.headers.get('oai-authenticated-user-id');const email=request.headers.get('oai-authenticated-user-email');const allowed=(env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);return {signedIn:!!id,isAdmin:!!id&&!!email&&allowed.includes(email.toLowerCase()),email:id?email:null};}
async function initialize(db){const marker=await db.prepare('SELECT id FROM cms_meta WHERE id = ?').bind('seed-v2-research').first();if(marker)return;await db.batch([...seedArticles.map(a=>db.prepare('INSERT OR IGNORE INTO articles (slug, status, published_at, document, revision) VALUES (?, ?, ?, ?, 1)').bind(a.slug,'published',a.publishedAt,JSON.stringify({...a,status:'published'}))),...seedWatchlist.map(w=>db.prepare('INSERT OR IGNORE INTO watch_items (symbol, document, revision) VALUES (?, ?, 1)').bind(w.symbol,JSON.stringify(w))),db.prepare('INSERT OR IGNORE INTO cms_meta (id) VALUES (?)').bind('seed-v2-research')]);}
const parse=row=>({...JSON.parse(row.document),revision:row.revision});
async function body(request){const raw=await request.text();if(raw.length>250000)fail('内容过大，请控制在 250 KB 内',413);try{return JSON.parse(raw);}catch{fail('提交内容格式不正确');}}
async function api(request,env){const url=new URL(request.url),path=url.pathname.replace(/\/$/,'');const user=identity(request,env);if(path==='/api/session')return json({...user,configured:!!env.ADMIN_EMAILS});const admin=path.startsWith('/api/admin/');if(admin&&!user.isAdmin)return json({error:user.signedIn?'当前账号没有管理权限':'请先登录管理员账号'},user.signedIn?403:401);if(!['GET','HEAD'].includes(request.method)){if(request.headers.get('origin')!==url.origin||!request.headers.get('content-type')?.startsWith('application/json'))return json({error:'请求来源或内容类型不正确'},403);}
 if(path==='/api/library'&&request.method==='GET')return json({videos:videos.map(v=>projectVideo(v,user.isAdmin)),courses});
 if(!env.DB)return json({error:'内容数据库暂时不可用，请稍后重试'},503);await initialize(env.DB);const db=env.DB;
 if((path==='/api/posts'||path==='/api/feed')&&request.method==='GET'){const rows=await db.prepare("SELECT document, revision FROM articles WHERE status = 'published'").all();const posts=rows.results.map(parse).map(a=>projectPost(a,user.isAdmin));if(path==='/api/feed')posts.push(...videos.map(v=>videoPost(projectVideo(v,user.isAdmin))));const params=Object.fromEntries(url.searchParams);const filters={query:params.q,contentType:params.type,market:params.market,stage:params.stage,symbol:params.symbol,tag:params.tag,month:params.month};return json(orderPosts(filterPosts(posts,filters),params.order==='asc'));}
 if(path.startsWith('/api/posts/')&&request.method==='GET'){const slug=decodeURIComponent(path.slice(11));const row=await db.prepare('SELECT document, revision, status FROM articles WHERE slug = ?').bind(slug).first();if(!row||(row.status!=='published'&&!user.isAdmin))return json({error:'研究记录不存在或尚未发布'},404);return json(projectPost(parse(row),user.isAdmin));}
 if(path==='/api/articles'&&request.method==='GET'){const rows=await db.prepare("SELECT document, revision FROM articles WHERE status = 'published' ORDER BY published_at DESC, slug ASC").all();return json(rows.results.map(parse).map(({sections,...a})=>({...a,images:projectPost(a,user.isAdmin).images})).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.publishedAt.localeCompare(a.publishedAt)));}
 if(path.startsWith('/api/articles/')&&request.method==='GET'){const slug=decodeURIComponent(path.slice(14));const row=await db.prepare('SELECT document, revision, status FROM articles WHERE slug = ?').bind(slug).first();if(!row||(row.status!=='published'&&!user.isAdmin))return json({error:'文章不存在或尚未发布'},404);const a=parse(row);const projected=projectPost(a,user.isAdmin);return json({...a,sections:projected.content,images:projected.images,locked:projected.locked});}
 if(path==='/api/watchlist'&&request.method==='GET'){const rows=await db.prepare('SELECT document, revision FROM watch_items ORDER BY symbol').all();return json(rows.results.map(parse));}
 if(path==='/api/admin/articles'&&request.method==='GET'){const rows=await db.prepare('SELECT document, revision FROM articles ORDER BY published_at DESC, slug').all();return json(rows.results.map(parse));}
 if(path==='/api/admin/watchlist'&&request.method==='GET'){const rows=await db.prepare('SELECT document, revision FROM watch_items ORDER BY symbol').all();return json(rows.results.map(parse));}
 if((path==='/api/admin/articles'||path==='/api/admin/watchlist')&&request.method==='PUT'){const input=await body(request);const isArticle=path.endsWith('/articles');const value=isArticle?article(input):watch(input);const key=isArticle?value.slug:value.symbol;const table=isArticle?'articles':'watch_items';const column=isArticle?'slug':'symbol';const revision=input.revision??0;if(!Number.isInteger(revision)||revision<0)fail('版本号不正确');if(!isArticle&&value.articleSlug){const linked=await db.prepare('SELECT status FROM articles WHERE slug = ?').bind(value.articleSlug).first();if(!linked||linked.status!=='published')fail('请关联已发布文章，或清空关联文章');}let result;if(revision===0){result=isArticle?await db.prepare('INSERT OR IGNORE INTO articles (slug,status,published_at,document,revision) VALUES (?,?,?,?,1)').bind(key,value.status,value.publishedAt,JSON.stringify(value)).run():await db.prepare('INSERT OR IGNORE INTO watch_items (symbol,document,revision) VALUES (?,?,1)').bind(key,JSON.stringify(value)).run();}else{result=isArticle?await db.prepare('UPDATE articles SET status = ?, published_at = ?, document = ?, revision = revision + 1 WHERE slug = ? AND revision = ?').bind(value.status,value.publishedAt,JSON.stringify(value),key,revision).run():await db.prepare('UPDATE watch_items SET document = ?, revision = revision + 1 WHERE symbol = ? AND revision = ?').bind(JSON.stringify(value),key,revision).run();}if(!result.meta.changes)return json({error:'标识已存在，或内容已在其他窗口更新。你的输入已保留，请重新载入后合并。'},409);return json({...value,revision:revision+1});}
 return json({error:'接口不存在'},404);
}
export default {async fetch(request,env,ctx){try{const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return await api(request,env);const match=url.pathname.match(/^\/articles\/([^/]+)\/?$/);if(match){url.pathname='/article/';url.search='?slug='+encodeURIComponent(match[1]);return Response.redirect(url.toString(),302);}if(!env.ASSETS)return new Response('Static assets unavailable',{status:503});return env.ASSETS.fetch(request);}catch(error){if(!error.status)console.error('CMS request failed',error);return json({error:error.status?error.message:'保存或读取失败，请稍后重试。当前输入不会被清空。'},error.status||503);}}};
