import http from 'node:http';
import {localImageStorage} from './local-image-storage.mjs';
import {readFileSync,existsSync,mkdirSync} from 'node:fs';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {adapter} from './sqlite-adapter.mjs';
import worker from '../dist/server/index.js';
// Development only: loopback listener; supplied identity headers are always removed.
mkdirSync('.local',{recursive:true});const sql=new DatabaseSync('.local/content.sqlite');
sql.exec('CREATE TABLE IF NOT EXISTS local_migrations (name TEXT PRIMARY KEY)');
if(!sql.prepare('SELECT name FROM local_migrations WHERE name = ?').get('0000_content')){sql.exec(readFileSync('drizzle/0000_content.sql','utf8'));sql.prepare('INSERT INTO local_migrations VALUES (?)').run('0000_content')}
for(const name of ['0001_image_uploads'])if(!sql.prepare('SELECT name FROM local_migrations WHERE name = ?').get(name)){sql.exec(readFileSync('drizzle/'+name+'.sql','utf8'));sql.prepare('INSERT INTO local_migrations VALUES (?)').run(name)}
const root=path.resolve('dist/client');const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.txt':'text/plain; charset=utf-8','.svg':'image/svg+xml','.ico':'image/x-icon'};
const env={DB:adapter(sql),IMAGES:localImageStorage(),ADMIN_EMAILS:'local-admin@localhost',ASSETS:{async fetch(request){let filename=path.resolve(root,'.'+decodeURIComponent(new URL(request.url).pathname));if(!filename.startsWith(root+path.sep)&&filename!==root)return new Response('Forbidden',{status:403});if(filename.endsWith(path.sep)||!path.extname(filename))filename=path.join(filename,'index.html');if(!existsSync(filename))return new Response(readFileSync(path.join(root,'404.html')),{status:404,headers:{'Content-Type':'text/html'}});return new Response(readFileSync(filename),{headers:{'Content-Type':types[path.extname(filename)]||'application/octet-stream'}})}}};
const server=http.createServer(async(req,res)=>{try{if(!['127.0.0.1:3000','localhost:3000'].includes(req.headers.host)){res.writeHead(403);return res.end('Loopback only')}const url=new URL(req.url,'http://'+req.headers.host);if(['/signin-with-chatgpt','/signout-with-chatgpt'].includes(url.pathname)){if(req.headers['sec-fetch-site']==='cross-site'){res.writeHead(403);return res.end()}const login=url.pathname==='/signin-with-chatgpt';res.writeHead(302,{'Location':login?'/admin/':'/','Set-Cookie':`local_editor=${login?'1':''}; Path=/; HttpOnly; SameSite=Strict${login?'':'; Max-Age=0'}`});return res.end()};const headers=new Headers();for(const [k,v]of Object.entries(req.headers)){if(!k.startsWith('oai-authenticated-user-')&&v)headers.set(k,Array.isArray(v)?v.join(','):v)}if((req.headers.cookie||'').split(';').some(c=>c.trim()==='local_editor=1')){headers.set('oai-authenticated-user-id','local-development');headers.set('oai-authenticated-user-email','local-admin@localhost')}const chunks=[];for await(const c of req)chunks.push(c);const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const response=await worker.fetch(request,env,{});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(e){console.error(e);res.writeHead(500);res.end('Local server error')}});
server.listen(3000,'127.0.0.1',()=>console.log('Local: http://127.0.0.1:3000 — development sign-in only; SQLite persists in .local/'));
